//
//  CityListWorkerTests.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 28/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PocketWorksWeather
import Quick
import Nimble

class CityListWorkerSpec: QuickSpec {
  // MARK: - Subject under test:
  var sut: CityListWorker!

  // MARK: - Spec:
  override func spec() {
    describe("CityListWorker") {
      beforeEach {
        self.sut = CityListWorker(apiService: PWSession.shared.apiService,
                                  cityListProvider: PWSession.shared)
      }
    }
  }
}
