//
//  CityListRouter.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CityListRoutingLogic {
  func routeToCityDetails()
}

protocol CityListDataPassing {
  var dataStore: CityListDataStore? { get }
}

class CityListRouter: NSObject, CityListRoutingLogic, CityListDataPassing {
  // MARK: - Model:
  weak var viewController: CityListViewController?
  var dataStore: CityListDataStore?

  // MARK: - Routing:
  func routeToCityDetails() {
    guard let selectedWeatherData = self.dataStore?.selectedWeatherData else {
      return
    }

    let cityDetailsVC = CityDetailsViewController.route(with: selectedWeatherData)
    self.viewController?.present(cityDetailsVC, animated: true, completion: nil)
  }
}
