//
//  CityListModels.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListCellVM { }

enum CityList {
  // MARK: - Use cases:
  enum GetCityList {
    struct Request { }
    struct Response {
      var weatherData: [CityWeatherResponse]
      var unitSystem: PWUnitSystem
    }
    struct ViewModel {
      var cityList: [CityListCellVM]
    }
  }

  enum ToggleUnitSystem {
    struct Request {
      var newUnitSystem: PWUnitSystem
    }
  }

  enum RegisterNewCity {
    struct Request {
      var city: PWCity
    }
    struct Response {
      var weatherData: CityWeatherResponse
    }
    struct ViewModel {
      var cellVM: CityListCellVM
    }
  }

  enum RemoveCity {
    struct Request {
      var selectedIndex: Int
    }
  }

  enum ReloadWeatherData {
    struct Response {
      var isReloading: Bool
    }
    struct ViewModel {
      var isReloading: Bool
    }
  }
}
