//
//  CityListPresenter.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListPresentationLogic {
  func presentGetCityList(_ response: CityList.GetCityList.Response)
}

class CityListPresenter: CityListPresentationLogic {
  // MARK: - Model:
  weak var viewController: CityListDisplayLogic?

  // MARK: - Public Funcs (Use cases):
  func presentGetCityList(_ response: CityList.GetCityList.Response) {
    var cellVMs = [CityListCellVM]()

    let actionCell = self.buildActionCellVM(with: response.unitSystem)
    cellVMs.append(actionCell)

    let viewModel = CityList.GetCityList.ViewModel(cityList: cellVMs)
    self.viewController?.displayGetCityList(viewModel)
  }

  // MARK: - Private Funcs:
  private func buildActionCellVM(with unitSystem: PWUnitSystem) -> CityListActionCell.ViewModel {
    return CityListActionCell.ViewModel(
      metricSystemButtonSelected: unitSystem == .metric,
      imperialSystemButtonSelected: unitSystem == .imperial)
  }
}
