//
//  CityListInteractor.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListBusinessLogic {
  func getCityList(_ request: CityList.GetCityList.Request)
  func toggleUnitSystem(_ request: CityList.ToggleUnitSystem.Request)
}

protocol CityListDataStore {
}

class CityListInteractor: CityListBusinessLogic, CityListDataStore {
  // MARK: - Model:
  var presenter: CityListPresentationLogic?
  var worker: CityListWorker?

  // MARK: - Public Funcs (Use cases):
  func getCityList(_ request: CityList.GetCityList.Request) {
    let response = CityList.GetCityList.Response(unitSystem: PWSession.shared.unitSystem)
    self.presenter?.presentGetCityList(response)
  }

  func toggleUnitSystem(_ request: CityList.ToggleUnitSystem.Request) {
    PWSession.shared.unitSystem = request.newUnitSystem
    let response = CityList.GetCityList.Response(unitSystem: PWSession.shared.unitSystem)
    self.presenter?.presentGetCityList(response)
  }
}
