//
//  CitySearchModels.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CitySearch {
  // MARK: - Use cases:
  enum UpdateResults {
    struct Request {
      var searchTerm: String
    }
    struct Response {
      var searchTerm: String
      var results: [PWCity]
    }
    struct ViewModel {
      var results: [CitySearchResultCell.ViewModel]
    }
  }

  enum ValidatingCityName {
    struct Response {
      var isValidating: Bool
    }
    struct ViewModel {
      var isValidating: Bool
    }
  }
}
