//
//  CitySearchWorker.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promises

class CitySearchWorker {
  var cityListProvider: CityListProvider

  init(cityListProvider: CityListProvider) {
    self.cityListProvider = cityListProvider
  }

  func searchForCity(using term: String) -> Promise<[PWCity]> {
    return self.cityListProvider
      .fetchCityList()
      .then(on: DispatchQueue.global(qos: .userInitiated)) { list -> [PWCity] in
        let filtered = list.filter({$0.name.contains(term)})
        return filtered
    }
  }
}
