//
//  CitySearchRouter.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CitySearchRoutingLogic {
  func routeBackToCityListWithSelectedCity()
}

protocol CitySearchDataPassing {
  var dataStore: CitySearchDataStore? { get }
}

class CitySearchRouter: NSObject, CitySearchRoutingLogic, CitySearchDataPassing {
  // MARK: - Model:
  weak var viewController: CitySearchViewController?
  var dataStore: CitySearchDataStore?

  // MARK: - Routing:
  func routeBackToCityListWithSelectedCity() {
    guard
      let cityListVC = self.viewController?.presentingViewController as? CityListViewController,
      let selectedCity = self.dataStore?.selectedCity
    else {
      return
    }

    self.viewController?.dismiss(animated: true) {
      cityListVC.register(newCity: selectedCity)
    }
  }
}
