//
//  CitySearchPresenter.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 27/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitySearchPresentationLogic {
  func presentUpdateResults(_ response: CitySearch.UpdateResults.Response)
  func presentValidatingCityName(_ response: CitySearch.ValidatingCityName.Response)
}

class CitySearchPresenter: CitySearchPresentationLogic {
  // MARK: - Model:
  weak var viewController: CitySearchDisplayLogic?

  // MARK: - Public Funcs (Use cases):
  func presentUpdateResults(_ response: CitySearch.UpdateResults.Response) {
    let results: [CitySearchResultCell.ViewModel] = response.results.map {
      let cityName = self.buildResultCityName(from: response.searchTerm, cityName: $0.name)
      return CitySearchResultCell.ViewModel(cityName: cityName)
    }
    let viewModel = CitySearch.UpdateResults.ViewModel(results: results)
    self.viewController?.displayUpdateResults(viewModel)
  }

  func presentValidatingCityName(_ response: CitySearch.ValidatingCityName.Response) {
    let viewModel = CitySearch.ValidatingCityName.ViewModel(isValidating: response.isValidating)
    self.viewController?.displayValidatingCityName(viewModel)
  }

  // MARK: - Private Funcs:
  private func buildResultCityName(from term: String, cityName: String) -> NSAttributedString {
    let attributedName = NSAttributedString(string: cityName)
      .applyFont(UIFont.systemFont(ofSize: 18.0))
      .applyForegroundColor(.white)

    let range = (cityName as NSString).range(of: term)
    if range.length > 0 {
      let boldName = NSMutableAttributedString(attributedString: attributedName)
      boldName.addAttribute(.font, value: UIFont.systemFont(ofSize: 18.0, weight: .bold), range: range)

      return boldName
    }

    return attributedName
  }
}
