//
//  CityDetailsWorkerTests.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 29/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PocketWorksWeather
import Quick
import Nimble

class CityDetailsWorkerSpec: QuickSpec {
  // MARK: - Subject under test:
  var sut: CityDetailsWorker!
  var apiSpy: StubbedPWAPIService!

  // MARK: - Spec:
  override func spec() {
    describe("CityDetailsWorker") {
      beforeEach {
        self.apiSpy = StubbedPWAPIService()
        self.sut = CityDetailsWorker(apiService: self.apiSpy)
      }

      afterEach {
        self.apiSpy = nil
        self.sut = nil
      }

      context("when get forecast for city id") {
        it("should ask api layer to get response") {
          waitUntil { done in
            self.sut.getForecastsData(for: "some id").then { data in
              expect(self.apiSpy.getCityWeatherForecastForCityCalled).to(beTrue())
              expect(data).to(equal([Seed.hanoiWeatherData]))
              done()
            }
          }
        }
      }
    }
  }
}
