//
//  CityDetailsWorker.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 28/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Promises

class CityDetailsWorker {
  var apiService: PWAPIServiceProtocol

  init(apiService: PWAPIServiceProtocol) {
    self.apiService = apiService
  }

  func getForecastsData(for cityId: String) -> Promise<[CityWeatherResponse]> {
    return self.apiService.getCityWeatherForecast(for: cityId)
  }
}
