//
//  CityDetailsInteractor.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 28/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityDetailsBusinessLogic {
  var openWeatherURL: URL { get }
  func showWeather(_ request: CityDetails.ShowWeather.Request)
}

protocol CityDetailsDataStore {
  var weatherData: CityWeatherResponse! { get set }
}

class CityDetailsInteractor: CityDetailsBusinessLogic, CityDetailsDataStore
{
  // MARK: - Model:
  var presenter: CityDetailsPresentationLogic?
  var worker: CityDetailsWorker?
  var weatherData: CityWeatherResponse!
  var openWeatherURL: URL {
    return URL(string: "https://openweathermap.org")!
  }

  // MARK: - Public Funcs (Use cases):
  func showWeather(_ request: CityDetails.ShowWeather.Request) {
    let response = CityDetails.ShowWeather.Response(weatherData: self.weatherData)
    self.presenter?.presentShowWeather(response)
  }
}
