//
//  CityDetailsModels.swift
//  PocketWorksWeather
//
//  Created by Anh Phan Tran on 28/07/2019.
//  Copyright (c) 2019 Anh Phan Tran. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CityDetails {
  // MARK: - Use cases:
  enum ShowWeather {
    struct Request { }
    struct Response {
      var weatherData: CityWeatherResponse
    }
    struct ViewModel {
      var cityName: String
      var mainWeather: String
      var windInfo: NSAttributedString
      var weekDay: String
      var maximumTemp: String
      var minimumTemp: String
      var weatherDescription: String
      var currentTemperature: String
      var humidityLevel: String
      var sunrise: String
      var sunset: String
      var pressure: String
      var visibility: String
    }
  }

  enum GetForecastData {
    struct Request { }
    struct Response {
      var forecastData: [CityWeatherResponse]
      var timezoneOffset: Double
    }
    struct ViewModel {
      var forecastVMs: [WindForecastCell.ViewModel]
    }
  }

  enum ToggleForecastLoading {
    struct Response {
      var isLoading: Bool
    }
    struct ViewModel {
      var isLoading: Bool
    }
  }

  enum ShowError {
    struct Response {
      var error: Error
    }
    struct ViewModel {
      var errorString: String
    }
  }
}
